name: sheliak-client
description: Client side for sheliak
ignoreFiles: .git .gitignore node_modules .next .vscode
modules:
- name: template
  language: nodejs14.x
  web: nextjs
  description: Module description
  functions:
  - name: entry
    entry: entry.js
    description: the entry point for the function