# Generated by Django 3.0.5 on 2021-03-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
