# Generated by Django 3.2.11 on 2022-02-06 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userlogin_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('', None)], max_length=1)),
                ('picture', models.URLField(blank=True, max_length=1024)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC')),
                ('address', models.TextField(blank=True)),
                ('invite_code', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=1024)),
                ('legacy_id', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
