# Generated by Django 3.2.11 on 2022-02-06 16:03
from django.db import migrations


class Migration(migrations.Migration):

    def separate_profiles_data(apps, schema_editor):
        User = apps.get_model('users', 'User')
        Profile = apps.get_model('users', 'Profile')
        for user in User.objects.all():
            profile = Profile.objects.create(user=user)
            profile.gender = user.gender
            profile.picture = user.picture
            profile.date_of_birth = user.date_of_birth
            profile.nationality = user.nationality
            profile.timezone = user.timezone
            profile.address = user.address
            profile.invite_code = user.invite_code
            profile.company = user.company
            profile.legacy_id = user.legacy_id
            profile.save()

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.RunPython(separate_profiles_data),
    ]
