# Generated by Django 3.2.11 on 2022-02-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220206_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invite_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logins_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
    ]
