# Generated by Django 3.2.15 on 2022-12-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220206_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extra_info',
            field=models.JSONField(default=dict),
        ),
    ]
