# Generated by Django 3.2.11 on 2022-01-23 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('backend', models.CharField(choices=[('SES', 'Amazon SES'), ('SMTP', 'SMTP'), ('CONSOLE', 'Console'), ('IN_MEMORY', 'Console'), ('DUMMY', 'Dummy'),], default='SES', max_length=10)),
                ('from_email', models.CharField(blank=True, max_length=256, null=True, verbose_name='Default From Email')),
                ('fail_silently', models.BooleanField(default=False, verbose_name='Fail Silently')),
                ('host', models.CharField(blank=True, max_length=256, null=True, verbose_name='Email Host')),
                ('port', models.SmallIntegerField(blank=True, null=True, verbose_name='Email Port')),
                ('username', models.CharField(blank=True, max_length=256, null=True, verbose_name='Email Authentication Username')),
                ('password', models.CharField(blank=True, max_length=256, null=True, verbose_name='Email Authentication Password')),
                ('use_tls', models.BooleanField(default=False, verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('timeout', models.SmallIntegerField(blank=True, null=True, verbose_name='Email Send Timeout (seconds)')),
                ('aws_access_key_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='AWS Access Key ID')),
                ('aws_secret_access_key', models.CharField(blank=True, max_length=256, null=True, verbose_name='AWS Secret Access Key')),
                ('aws_ses_region_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='AWS SES Region Name')),
                ('aws_ses_region_endpoint', models.CharField(blank=True, max_length=256, null=True, verbose_name='AWS SES Region Endpoint')),
                ('aws_ses_auto_throttle', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('aws_ses_config', models.CharField(blank=True, max_length=256, null=True)),
                ('dkim_domain', models.CharField(blank=True, max_length=256, null=True)),
                ('dkim_key', models.CharField(blank=True, max_length=256, null=True)),
                ('dkim_selector', models.CharField(blank=True, max_length=256, null=True)),
                ('dkim_headers', models.CharField(blank=True, max_length=256, null=True)),
                ('aws_ses_source_arn', models.CharField(blank=True, max_length=256, null=True)),
                ('aws_ses_from_arn', models.CharField(blank=True, max_length=256, null=True)),
                ('aws_ses_return_path_arn', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Email',
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('site_title', models.CharField(blank=True, max_length=256, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stacks.email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
